builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
    - linux
  id: kube-aws-node-labeler
  main: ./cmd/aws-node-labeler/main.go
dockers:
  -
    goos: linux
    goarch: amd64
    binaries:
    - kube-aws-node-labeler
    image_templates:
    - "gianarb/kube-aws-node-labeler:latest"
    - "gianarb/kube-aws-node-labeler:{{ .Tag }}"
    - "gianarb/kube-aws-node-labeler:v{{ .Major }}"
    skip_push: false
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
